### ISSUE TITLE
Nhận xét từ thành viên 1 của nhóm 5

### ISSUE THREAD

**Issue by IceIce1ce** [huutuan122/P4DS_Final#7]
1) Mình nghĩ bạn nên tách thành 2 phần tiền xử lý riêng cho các cột categorical và numerical ở phần tiền xử lý giá trị thiếu
2) Phần các giá trị của dữ liệu được phân bố như thế nào cũng nên tách làm 2 phần cho categorical và numerical
3) Ở câu hỏi 3 mình nghĩ bạn nên mở rộng thêm vì sao chủ nhà Sonder nhận được nhiều review từ khách hàng nhất, do chủ nhà đó giá cho thuê rẻ hơn các chủ nhà khác hay sao?
4) Ở câu hỏi 4 mình cũng thấy chưa ổn lắm vì ở câu hỏi 3 chủ nhà Sonder nhận được review cao nhất nhưng trong 10 đêm lại ít có lợi nhất nhưng chủ nhà Maya có ít review nhất nhưng lại được nhiều khách hàng lựa chọn để ở nhiều nhất trong 10 đêm, mình nghĩ nên phân tích để hiểu hơn ở chỗ này

**Comment by huutuan122** [comment]
Ok mình cảm ơn bạn đã để lại lời nhận xét <3
