### ISSUE TITLE
Nhận xét #2 của nhóm 05

### ISSUE THREAD

**Issue by stark4079** [huutuan122/P4DS_Final#8]
Câu 1 giá nhà hay giá cho thuê nhà; thay đổi theo thời gian chứ bạn 
- Phần đặt câu hỏi nên đánh số cho câu hỏi luôn.
- Cell 33 cột price: lỗi mardown
- Câu 2 mình nghĩ bạn nên hỏi giá của từng loại phòng theo khu vực khác nhau như thế nào?, còn nếu là nên chọn khu vực nào để thuê thì bạn nên sort trước khi trực quan để dễ nhìn.
- Hình như câu 4 chưa rõ ràng lắm nhé, nữa review xấu thì sao?
- Nhóm bạn chưa có đường dẫn tới github ở đầu file jupyter như thầy yêu cầu và chưa có file hướng dẫn chạy cũng như chưa có hướng dẫn chạy ở file *README.md*.

**Comment by huutuan122** [comment]
Ok mình cảm ơn bạn đã để lại lời nhận xét <3
